name: cmip6_omz
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - ipykernel
  - astropy
  - dask
  - distributed
  - dask-jobqueue
  - cartopy
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas<1.3.0 # had numerous problems with the time indexing...
  - matplotlib
  - cmocean
  - regionmask
  - xesmf
  - xhistogram
  - zarr
  - gsw
  - numba
  - h5netcdf
  - pip
  - cf_xarray
  - rechunker<=0.3.3
  - fastjmd95
  - nc-time-axis
  - xarrayutils
  - intake-esm
  - xgcm
  #- cmip6_preprocessing
  - pip
  - pip:
      - git+https://github.com/jbusecke/cmip6_preprocessing.git
