name: test_env_cmip6_omz
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - cmip6_preprocessing
  - cartopy
  - xarrayutils
  - regionmask
  - xgcm
  - cf_xarray
  - numba
  - zarr
  - rechunker<=0.3.3
  ##############
  - Pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
