name: test_env_cmip6_omz
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - cmip6_preprocessing
  - xarrayutils
  - regionmask
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
